import { BrowserRouter, Routes, Route, Navigate } from "react-router-dom";
import { ThemeProvider } from "./shared/components/theme-provider";
import { I18nProvider } from "./shared/i18n/I18nProvider";
import { MainLayout } from "./shared/layouts/MainLayout";
import DashboardPage from "./modules/analytics/DashboardPage";
import SystemHealthPage from "./modules/analytics/SystemHealthPage";
import LandingPage from "./modules/landing/LandingPage";
import AboutPage from "./modules/about/AboutPage";
import BlogResourcePage from "./modules/resources/BlogResourcePage";
import ResourceLibraryPage from "./modules/resources/ResourceLibraryPage";
import BlogDetailPage from "./modules/resources/BlogDetailPage";
import ResourceDetailPage from "./modules/resources/ResourceDetailPage";
import FaqPage from "./modules/faq/FaqPage";
import ContactPage from "./modules/contact/ContactPage";
import PrivacyPolicyPage from "./modules/legal/PrivacyPolicyPage";
import TermsOfServicePage from "./modules/legal/TermsOfServicePage";
import CookiesPolicyPage from "./modules/legal/CookiesPolicyPage";
import CrowdsourcingListingPage from "./modules/reports/CrowdsourcingListingPage";
import CrowdsourcingDetailPage from "./modules/reports/CrowdsourcingDetailPage";
import ReportSubmissionPage from "./modules/reports/ReportSubmissionPage";