name: Deploy Frontend (Caddy)

on:
  push:
    branches:
      - main
      - dev
      - stage

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4